apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xs0pbo70o-nodejs
  janus-idp.io/tekton: xs0pbo70o-nodejs
  backstage.io/kubernetes-id: xs0pbo70o-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xs0pbo70o-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
